### ISSUE TITLE
Cannot find symbol BulletApplicationComponent

### ISSUE THREAD

**Issue by bryant1410** [tbroyer/bullet#5]
Sometimes (like half of the time) it throws an error while compiling that says that it cannot find the symbol BulletApplicationComponent. The thing is that it is there! It was generated. It seems like at the exact time it tries to use it, it isn't there, but after that it is.

Due to the fact that it doesn't happen always and that the generated file appears when I look at the error, I strongly think this is a race condition. Maybe between Gradle tasks or maybe a bug in bullet.

Anyway, what could be happening? And, btw, how can I debug the bullet apt usage? Or view the dependencies between Gradle tasks?

**Comment by tbroyer** [comment]
Do you have a repro-case? Are you using [incremental compilation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:incremental)? or a non-Java language such as Groovy or Kotlin?

Also, how are you configuring your Gradle build to use Bullet? Nothing special? (just put Bullet in the classpath) Manually? through the `android-apt` plugin? the `net.ltgt.apt` plugin?
And how are you checking that "it is there"? Looking for the `.java` or the `.class`?

Anyway, I doubt there could be a race condition between Gradle tasks, as I'd expect code that depends on the generated class to be compiled either within the same task or in tasks that depend on that task (so can't be executed in parallel), and it cannot be a race condition within the Java compiler either, as I don't think it parallelizes anything.

**Comment by bryant1410** [comment]
I'm using incremental compilation and just Java, not Groovy nor Kotlin. I use it in [AndroidBaseProject](https://github.com/xmartlabs/AndroidBaseProject) for instance. Yes, I do use the android-apt plugin. The "it is there" check is that the generated .java is there (didn't check for the .class file).

**Comment by bryant1410** [comment]
Maybe a race condition with the annotation processors?

**Comment by bryant1410** [comment]
btw, this change in [auto-common](https://github.com/google/auto/commit/8f078e0e3e7821ffda93ce0b28f1f9bd7d8cef31) could be exploited by bullet?

**Comment by bryant1410** [comment]
Also tried updating all the libraries [in a fork](https://github.com/xmartlabs/bullet), but didn't work

**Comment by tbroyer** [comment]
Well, the problem is with the Gradle build. Running `./gradlew assembleDebug --debug` (to avoid any `validateReleaseSigning` task that would fail because I don't have a keystore setup), we can see that, when it fails, the `:app:compileProductionDebugJavaWithJavac` task is passed the `ApplicationComponent.java` as input, but the `:app:compileStagingDebugJavaWithJavac` is not, and fails. We can also see that the failing task starts with deleting the `DaggerApplicationComponent.class` and `BulletApplicationComponent.class`.

I unfortunately don't know enough about the Android build (and which tasks it creates and how it configures them) and the other plugins you're using that could influence the build (retrolambda, etc.) to debug any further, but the bug is not in Bullet.

BTW, the reason you can find the generated sources in all cases is that the android-apt plugin doesn't declare the generated-sources output folder as an output for the compile task, so it's never cleaned. My `net.ltgt.apt` plugin for instance (but it probably doesn't support Android builds) does so, so a `./gradlew cleanCompileJava` will delete the generated sources too, whereas a `./gradlew cleanCompileStagingDebugJavaWithJavac in your case only deletes compiled classes, not the generated sources (you'll still find `app/build/generated/source/apt/staging/debug/com/xmartlabs/template/BulletApplicationComponent.java`, but not `app/build/retrolambda/stagingDebug/com/xmartlabs/template/BulletApplicationComponent.class`)

**Comment by bryant1410** [comment]
Ah! Thanks for the help man!! :smile:

**Comment by tbroyer** [comment]
See google/dagger#298

**Comment by bryant1410** [comment]
Good to know. Maybe this is the cause

**Comment by bryant1410** [comment]
Just for the record, we have tried without the incremental option, and this still happens
